Work on documentation issues
VDVde/OJP pull request #154
Opened 2021-03-18 17:19 UTC by jmaerki

As per the last telco, I present my first merge request for documentation changes on the 1.1 branch. This work is still ongoing.

2021-05-06 10:22 UTC, sgrossberndt commented
Could you update to the latest state here please?

2021-05-06 10:30 UTC, sgrossberndt requested changes

2021-05-06 10:30 UTC, sgrossberndt commented on OJP/OJP_FareSupport.xsd
> +			<xs:element name="MinimumBookingPeriod" type="xs:duration" minOccurs="0">
Errors in the XSD files should be fixed in separate commits

2021-05-06 10:30 UTC, sgrossberndt commented on OJP/OJP_PlaceSupport.xsd
> +		<xs:documentation>OJP/OJP_PlacesSupport.xsd - Supporting definitions for place information</xs:documentation>
Errors in the XSD files should be fixed in separate commits

2021-05-06 10:30 UTC, sgrossberndt commented on docs/check-ojp-schemas.sh
> +#!/bin/bash
This script must be added to https://github.com/VDVde/OJP/blob/changes_for_v1.1/.travis.yml#L7, `xsltproc` is already defined as a dependency to be installed here https://github.com/VDVde/OJP/blob/changes_for_v1.1/.travis.yml#L4

2021-05-31 16:01 UTC, jmaerki commented
I think I'm finally done with pretty much all open issues.

2021-06-21 13:23 UTC, sgrossberndt commented
https://github.com/VDVde/OJP/pull/163 should be merged first and this pull request rebase afterwards. Codewise it looks fine, @skinkie mentioned that @schlpbch found some issues with tables, maybe he could add them either here (or create an issue)?

2021-06-21 13:24 UTC, sgrossberndt commented on OJP/OJP_FareSupport.xsd
> +			<xs:element name="MinimumBookingPeriod" type="xs:duration" minOccurs="0">
See https://github.com/VDVde/OJP/pull/163

2021-07-14 10:29 UTC, sgrossberndt commented
Hello @jmaerki, please rebase this pull request so we can merge it.

2021-07-21 07:54 UTC, jmaerki commented
I'm not a daily Git user and have never worked with rebase and do not yet know exactly how that works. I currently lack the time to educate myself on it in order not to mess up. So I've done what I could and just merged the latest changes on changes_for_v1.1 to the doc_issues branch. I hope this is enough. In case it is not, I've added write access to @sgrossberndt to my repo in the hopes that this helps. Otherwise, please allow a few more days so I can make time to educate myself on "rebase".

2021-08-02 10:16 UTC, sgrossberndt commented
Hi @jmaerki, your last action https://github.com/VDVde/OJP/pull/154/commits/9a1083287991f25ed550b27d7f546ff59c2de3fb was exactly the step needed. Thanks

2021-08-02 10:30 UTC, sgrossberndt requested changes

2021-08-02 10:30 UTC, sgrossberndt commented on .travis.yml
>    - sudo apt-get install -qq libxml2-utils xsltproc asciidoctor
As asciidoctor is no longer needed it should not be installed at all

2021-08-02 10:30 UTC, sgrossberndt commented on docs/README.md
> +# OJP Documentation
Maybe use `# Generating OJP Documentation` instead to make it more clear from the header already this is not the documentation itself?

2021-08-02 10:30 UTC, sgrossberndt commented on docs/ojp-to-asciidoc.xsl
>  (C) cantamen/Dirk Hillbrecht 2017
As asciidoc is no longer used is this xsl file obsolete and can be removed?

2021-08-02 10:30 UTC, sgrossberndt commented on docs/schema-collection.xml
> +    <xi:include href="../OJP/OJP_RequestSupport.xsd"/>
indent

2021-08-18 14:46 UTC, sgrossberndt commented
Hi @jmaerki , could you please update this pull request?

2021-08-23 13:42 UTC, jmaerki commented
Done. Sorry for the delay. Busy times.

2021-08-23 15:04 UTC, sgrossberndt approved these changes

2021-08-25 09:46 UTC, skinkie approved these changes

2021-08-25 09:46 UTC, sgrossberndt commented
Rendering can be seen here: https://jmaerki.github.io/OJP/generated/OJP.html#PointOfInterestRefStructure

2021-08-25 09:55 UTC, merged