added the error messages from the documenation
VDVde/OJP pull request #203
Opened 2022-06-01 18:56 UTC by ue71603

Fixes: https://github.com/VDVde/OJP/issues/111

2022-08-23 09:55 UTC, sgrossberndt requested changes
We have to discuss this change again.

1. This list currently only consists of `StopEventResponse` from the documentation, which now is `OJPStopEventDelivery`. But apparently when I removed unused structures in [0168dcd4](https://github.com/VDVde/OJP/commit/0168dcd4#diff-93bff6186bd1e221585808083d9cbb5da7cbddfab534ebf013679ff3d5596274L152) it was overlooked these `ErrorMessage`s are not part of the output at all.
I wonder now whether this was the correct choice back then to simply remove these structures - how are error messages regarding a whole response transported now? The current state seems to only be able to transport an error message for a single `StopEventResult`, but not for the whole `OJPStopEventDelivery`. Do we have to re-add `ErrorMessage` at a base delivery level?

2. Is `Code` in `ErrorMessageStructure` the correct place to document all the codes for all the responses or should they rather be documented each in the `ErrorMessage` where they may occur, e.g. https://github.com/VDVde/OJP/blob/changes_for_v1.1/OJP/OJP_StopEvents.xsd#L194

3. Currently there are only the error codes of some stopEvent documented in the xsd in this commit, the documentation has a lot more, e.g. `STOPEVENT_LASTSERVICEOFTHISLINE`, `FARES_STOPPOINTUNKNOWN`, ... which are missing here.

2022-08-25 21:56 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					STOPEVENT_LOCATIONUNKNOWN:The location (address, stop etc.) for which stop events have been requested is unknown.
fixed

2022-08-25 21:58 UTC, ue71603 commented
@sgrossberndt  You have a lengthy comment here. It seems it does not relate to this change. Should we discuss it in a separate issue? Can you create it then?

> We have to discuss this change again.
> 
> 1. This list currently only consists of `StopEventResponse` from the documentation, which now is `OJPStopEventDelivery`. But apparently when I removed unused structures in [0168dcd4](https://github.com/VDVde/OJP/commit/0168dcd4#diff-93bff6186bd1e221585808083d9cbb5da7cbddfab534ebf013679ff3d5596274L152) it was overlooked these `ErrorMessage`s are not part of the output at all.
>    I wonder now whether this was the correct choice back then to simply remove these structures - how are error messages regarding a whole response transported now? The current state seems to only be able to transport an error message for a single `StopEventResult`, but not for the whole `OJPStopEventDelivery`. Do we have to re-add `ErrorMessage` at a base delivery level?
> 2. Is `Code` in `ErrorMessageStructure` the correct place to document all the codes for all the responses or should they rather be documented each in the `ErrorMessage` where they may occur, e.g. https://github.com/VDVde/OJP/blob/changes_for_v1.1/OJP/OJP_StopEvents.xsd#L194
> 3. Currently there are only the error codes of some stopEvent documented in the xsd in this commit, the documentation has a lot more, e.g. `STOPEVENT_LASTSERVICEOFTHISLINE`, `FARES_STOPPOINTUNKNOWN`, ... which are missing here.

2022-08-30 08:33 UTC, sgrossberndt commented
No, this lengthy comment is exactly about this change. There is no use merging this pull request before we have discussed the points in this comment. In order to be able to find it for the discussion I will add it to the issue though.

2022-10-18 17:33 UTC, ue71603 commented
* For the single result level ErrorMessage can be used.
* We have ServiceDelivery/ErrorCondition for general high level errors: 
![image](https://user-images.githubusercontent.com/24227470/196497593-e6e54c25-da59-4905-827a-8ea7a63950ed.png)
* We also have OJPExchancePointDelivery/ErrorCondition: 
![image](https://user-images.githubusercontent.com/24227470/196498037-31e58062-7360-4e74-b83d-c778029e765f.png) 
This is still very abstract.

One idea would be  for Delivery level errors would be to add a ServiceDeliveryErrorGroup. It that for simplicities sake, I would like to put multiple ErrorMessageStructures. However, this is not possible, because DeliveryStatusGroup belongs to Siri

I will try to put it into the ServiceResponseContextGroup
![image](https://user-images.githubusercontent.com/24227470/196500889-d5eb06fa-9ea6-4776-b948-02e681e02f6b.png)


Then I would like to formalize ErrorMessageStructure (but not having a different one per request/response:
* Code as Enum
* Text for the description
* LogDatan as xs:string

The code is then expanded from
* OJP specification
* SIRI
* TRIAS

2022-10-18 17:46 UTC, ue71603 commented
* SIRI is already included in the ErrorCondition, but was not fully helpful
* Started copying codes from the specification. @trurlurl  could you continue? The eumeration is ErrorCodeEnumeration in OJP_Commons.xsd and in the specification you search for "possible errors"
* @sgrossberndt  It seems to me that TRIAS uses the same codes in the specification document as OJP. But I only have the 1.2 file.  Is the 1.4 out already?

2022-10-19 07:22 UTC, sgrossberndt commented
You can find TRIAS releases at https://github.com/VDVde/TRIAS/releases, most recent is v1.3 but v1.4 will be released in the near future

2022-11-03 08:13 UTC, trurlurl commented
@ue71603 I added a bunch of error codes. Current state:

All error codes from OJP specs should be there

Additionally from Trias (assuming / guessing that implementation of the corresponding requests is planned):

REFINE
ROUTE

Found in Trias but not added:

BOOKING
BOOKINGINFO
MAP
FACILITYSTATUSREPORT
FACILITYREQUEST
ALERT
PERSONALISATIONSAVEVALUEREQUEST
PERSONALISATIONDELETEVALUEREQUEST
PERSONALISATIONSAVETRIPREQUEST
PERSONALISATIONRETRIEVETRIPREQUEST
PERSONALISATIONDELETETRIPREQUEST
POSITIONING
CONNECTIONDEMAND
CONNECTIONSTATUS
CONNECTIONREPORT
SERVICEREGISTER
AUTH

**### Missing:** AVAILABILITY (or BOOKINGAVAILABILITY?) for AvailabilityRequest
AvailabilityRequest is not yet documemented for Trias (1.3), no error codes found in the code base.

2022-11-04 08:49 UTC, ue71603 reviewed
OK. Additional error messages we can add ad any time.

2022-11-04 08:50 UTC, ue71603 commented
@sgrossberndt  As you did some work on this. Can you agree with the way we propose now to do it?

2022-11-04 11:24 UTC, sgrossberndt requested changes
The current state addresses [point 1 of my comment](https://github.com/VDVde/OJP/pull/203#pullrequestreview-1081739814) by adding a `Problem` element to `ServiceResponseContextGroup` - that's good.

The current state still puts all error codes in one structure though - [point 2 of my comment](https://github.com/VDVde/OJP/pull/203#pullrequestreview-1081739814) aimed at whether it would be better to have e.g. a `GeneralOJPProblemTypeEnumeration` in the `ServiceResponseContextGroup` only containing the `OJPGENERIC_*` codes and e.g. a `FaresProblemTypeEnumeration` only containing the fare specific codes (`FARES_*`).

The current state addresses [point 3 of my comment](https://github.com/VDVde/OJP/pull/203#pullrequestreview-1081739814), that's good.

As stated in another pull request we currently do not render the annotation of enumerations as visible [in the preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/VDVde/OJP/0e4c890e4d907f8aa8d935d911c8ab244494c1cd/docs/generated/OJP.html#ProblemTypeEnumeration) - it is very good to have those annotations, we have to come up with a solution to render them I guess..

2022-11-04 11:24 UTC, sgrossberndt commented on OJP/OJP_Common.xsd
> +					<xs:documentation>Fare calculation is not possible because the suggested trip is not in compliance with the fare regulations (eg: because of round trips, TripLegs that go forth and return or exc
`e.g.:` instead of `eg:`

2022-11-04 11:24 UTC, sgrossberndt commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The trip planning result suggest a service which is not permitted by the fare authority.</xs:documentation>
`suggests` instead of `suggest`

2022-11-04 11:24 UTC, sgrossberndt commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The server does not support the specific request (eg: MultiPointTripRequest).</xs:documentation>
`e.g.:` instead of `eg:`

2022-11-04 11:24 UTC, sgrossberndt commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The server does not support the requested feature (eg: parameter NotVia in TripRequest).</xs:documentation>
`e.g.:` instead of `eg:`

2022-11-04 22:50 UTC, ue71603 commented on OJP/OJP_Fare.xsd
>  					<xs:documentation>Result-specific error messages.</xs:documentation>
done

2022-11-04 22:50 UTC, ue71603 commented on OJP/OJP_FareSupport.xsd
>  					<xs:documentation>Result-specific error messages </xs:documentation>
done

2022-11-04 22:51 UTC, ue71603 commented on OJP/OJP_RequestSupport.xsd
> +					<xs:documentation>OJP specific error messages for the whole delivery.</xs:documentation>
done

2022-11-04 22:52 UTC, ue71603 commented on OJP/OJP_StopEvents.xsd
>  					<xs:documentation>Error messages that refer to this stop event.</xs:documentation>
done

2022-11-04 22:52 UTC, ue71603 commented on OJP/OJP_Trips.xsd
>  					<xs:documentation>Error messages related to this trip result.</xs:documentation>
done

2022-11-04 22:53 UTC, ue71603 commented on OJP/OJP_Trips.xsd
>  					<xs:documentation>Error messages related to trip result.</xs:documentation>
done

2022-11-04 22:54 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +			<xs:documentation>All error codes</xs:documentation>
done

2022-11-04 22:54 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The server does not support the requested feature (eg: parameter NotVia in TripRequest).</xs:documentation>
done

2022-11-04 22:55 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The trip planning result suggest a service which is not permitted by the fare authority.</xs:documentation>
done

2022-11-04 22:55 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>Fare calculation is not possible because the suggested trip is not in compliance with the fare regulations (eg: because of round trips, TripLegs that go forth and return or exc
done

2022-11-04 22:55 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +			<xs:enumeration value="EXCHANGEPOINTS _UNKNOWNDESTINATION">
done

2022-11-04 22:55 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +			<xs:enumeration value="EXCHANGEPOINTS _UNKNOWNADJACENTSYSTEM">
done

2022-11-04 22:56 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The requested departure time at each origin locations is after the requested arrival time at any destination location.</xs:documentation>
done

2022-11-04 22:58 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>In case a multi-point request with MultiPointType set to eachDestination could not be responded with a trip solution to each of the destination points. And respectively in case
done

2022-11-04 22:58 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>In case a multi-point request uses too many points as departure or arrival.</xs:documentation>
done

2022-11-04 22:59 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>The maximum time allowed for using modes of individual transport (mostly walking or cycling) has been extended by the system because otherweise no trip could be found.</xs:docu
done

2022-11-04 23:01 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +			<xs:enumeration value="ROUTE_NOROUTEFOUND">
currently I put it into a comment. We can remove it at the end.

2022-11-04 23:02 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>if the error can not be found from the list above</xs:documentation>
done

2022-11-04 23:02 UTC, ue71603 commented on OJP/OJP_Common.xsd
>  			<xs:documentation>Structured error messages</xs:documentation>
done

2022-11-04 23:03 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +			<xs:element name="Detail" type="InternationalTextStructure" minOccurs="0">
Wrote Details

2022-11-04 23:04 UTC, ue71603 commented on OJP/OJP_Common.xsd
> +					<xs:documentation>If additional log data is provided.</xs:documentation>
done

2022-11-04 23:47 UTC, ue71603 commented
@sgrossberndt  @skinkie 
About this point: T`he current state still puts all error codes in one structure though - https://github.com/VDVde/OJP/pull/203#pullrequestreview-1081739814 aimed at whether it would be better to have e.g. a GeneralOJPProblemTypeEnumeration in the ServiceResponseContextGroup only containing the OJPGENERIC_* codes and e.g. a FaresProblemTypeEnumeration only containing the fare specific codes (FARES_*).`

Can you please discuss this and tell me which way you want to go.

About this point:` As stated in another pull request we currently do not render the annotation of enumerations as visible [in the preview](https://htmlpreview.github.io/?https://raw.githubusercontent.com/VDVde/OJP/0e4c890e4d907f8aa8d935d911c8ab244494c1cd/docs/generated/OJP.html#ProblemTypeEnumeration) - it is very good to have those annotations, we have to come up with a solution to render them I guess..`

This is addressed in: https://github.com/VDVde/OJP/issues/255, so I would like to not process it here.

2022-11-09 15:47 UTC, herlitze commented
I am also torn. I see the proposed solution with a structure but subcategories in the enum name as a good compromise

2022-11-24 12:18 UTC, skinkie approved these changes
I still wonder why we change ErrorMessage to "Problem" maybe this choice of words can be explained.

2022-11-24 14:17 UTC, ue71603 commented
Part of the commit message: https://datatracker.ietf.org/doc/html/rfc7807 and also. Errorstructures by Service (and perhaps a general one) and have a complete list as annex to the standard rendered by the documentation engine.

2022-12-06 16:39 UTC, ue71603 commented
@sgrossberndt  updated: Is this ok for you now?

2022-12-07 12:24 UTC, sgrossberndt submitted a review, later dismissed
Proposal for commit message when squashing:

* Renamed `ErrorMessage` to `Problem` in accordance to [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807#section-4-1), `Code` to `Type`, `Text` to `Title` and added `Details` and `LogData`
* Added dedicated ProblemStructures for each request, enumerating the possible types, some of which were previously only defined in the documentation, some not defined at all.
* Added the `Problem` element to `PlaceResultStructure` and `TripInfoResultStructure`
* Added the `Problem` element to `FareResultStructure` so `StopFareResult` and `StaticFareResult` may also contain one and removed it from `TripFareResult` and `MultiTripFareResult`
* Renamed some problem types (in comparison to the former documentation):
  * `FARES_*` to `FARE_*`
  * `MULTIPOINTTRIP_NOTALLPOINTSCOVERED` to `TRIP_MULTIPOINT_NOTALLPOINTSCOVERED`
  * `MULTIPOINTTRIP_TOOMANYPOINTS` to `TRIP_MULTIPOINT_TOOMANYPOINTS`

2022-12-12 08:34 UTC, herlitze approved these changes

2022-12-15 14:35 UTC, skinkie commented on OJP/OJP_Places.xsd
> +			<xs:element name="WaitDuration" type="xs:duration" default="PT0M" minOccurs="0">
```suggestion
			<xs:element name="WaitDuration" type="xs:duration" minOccurs="0" default="PT0M">
```

2022-12-15 14:45 UTC, sgrossberndt approved these changes

2022-12-16 09:08 UTC, skinkie approved these changes

2022-12-16 09:09 UTC, merged