Feature TypeOfProductCategoryFilter.
VDVde/OJP pull request #227
Opened 2022-08-08 15:03 UTC by skinkie

Fix #166

2022-08-08 16:21 UTC, ue71603 submitted a review, later dismissed

2022-08-19 13:45 UTC, Aurige commented on OJP_Common.xsd
> +	<xs:simpleType name="TypeOfProductCategoryType">
I guess you mean TypeOfProductCategoryIdType (to reference a TypeOfProductCategory via its Id) ?

2022-08-19 16:19 UTC, skinkie commented on OJP_Common.xsd
> +	<xs:simpleType name="TypeOfProductCategoryType">
```suggestion
	<xs:simpleType name="TypeOfProductCategoryIdType">
```

2022-08-19 16:19 UTC, skinkie commented on OJP_Common.xsd
> +			<xs:extension base="TypeOfProductCategoryType"/>
```suggestion
			<xs:extension base="TypeOfProductCategoryIdType"/>
```

2022-08-21 16:06 UTC, ue71603 approved these changes

2022-08-22 06:46 UTC, Aurige approved these changes

2022-09-28 08:41 UTC, sgrossberndt reviewed
What is a "type of product category"? How does a TypeOfProductCategoryId differ from a ProductCategoryId? Is this really needed?

OJP_Common.xsd already defines `ProductCategoryCodeType` (also siri_feature_support-v2.0.xsd, see https://github.com/VDVde/OJP/issues/249)

In case a "type of product category" is additionally needed please add explanations to the xsd annotations, so its possible to understand the difference.

2022-09-28 09:00 UTC, sgrossberndt requested changes
What is a "type of product category"? How does a TypeOfProductCategoryId differ from a ProductCategoryId? Is this really needed?

OJP_Common.xsd already defines ProductCategoryCodeType (also siri_feature_support-v2.0.xsd, see https://github.com/VDVde/OJP/issues/249)

In case a "type of product category" is additionally needed please add explanations to the xsd annotations, so its possible to understand the difference.

2022-10-01 15:27 UTC, ue71603 commented
If ok also for @Aurige I will simplify this and not include new structures.

2022-10-03 15:36 UTC, Aurige commented on OJP_Common.xsd
> +			<xs:element name="TypeOfProductCategoryRef" type="TypeOfProductCategoryRefStructure" minOccurs="0" maxOccurs="unbounded"/>
should just ref the element from line92

2022-10-03 15:36 UTC, Aurige commented
I agree that the structure is a bit heavy and weird: you have a 	<xs:element name="TypeOfProductCategoryRef" type="TypeOfProductCategoryRefStructure"> that is never used  (line 107 should just refer it)

2022-10-18 15:18 UTC, ue71603 commented on OJP_Common.xsd
> +			<xs:element name="TypeOfProductCategoryRef" type="TypeOfProductCategoryRefStructure" minOccurs="0" maxOccurs="unbounded"/>
done

2022-10-19 07:01 UTC, sgrossberndt requested changes
This pull request is against master instead of changes_for_v1.1. When I tried to rebase the branch against changes_for_v1.1 I found out that branch already contains a ProductCategoryFilter from https://github.com/VDVde/OJP/pull/95. I guess this pull request and its branch are obsolete and can be removed?

2022-10-19 07:27 UTC, closed without merging