Obsolete code in OJP_RequestSupport,xsd
VDVde/OJP pull request #294
Opened 2023-01-11 17:08 UTC by trurlurl

The removed elements don't seem to be used anywhere in the XSD. Is it really o.k. to remove them?

2023-01-12 08:55 UTC, ue71603 approved these changes

2023-01-12 09:18 UTC, Aurige approved these changes

2023-01-13 09:36 UTC, skinkie requested changes
I would not want to use the SubscriptionRequest. Does the subscription request itself exist with the removal of the SubscriptionRequestContextGroup?

2023-01-20 14:28 UTC, ue71603 commented
Norman: Does this come from TripMonitoring?
Stephan: Guess it was.
So we can remove it now. If we do TripMonitoring we can do it.
Stefan: Concur. I want TripMonitoring

2023-01-20 14:29 UTC, sgrossberndt approved these changes

2023-01-20 14:29 UTC, Aurige approved these changes

2023-01-20 14:34 UTC, skinkie approved these changes

2023-01-20 14:51 UTC, skinkie approved these changes

2023-01-20 14:52 UTC, sgrossberndt approved these changes

2023-01-20 14:52 UTC, merged