Update CHANGELOG.md
VDVde/OJP pull request #309
Opened 2023-01-20 22:08 UTC by ue71603

This is the PR to update the changelog.

2023-01-23 13:03 UTC, trurlurl commented on CHANGELOG.md
> +### Added
```suggestion
### Added
* New 'OJPLineInformationRequest' and 'OJPLineInformationDelivery' ([#243](https://github.com/VDVde/OJP/pull/243), [#308](https://github.com/VDVde/OJP/pull/308))
* New 'OJPAvailabilityRequest' and 'OJPAvailabilityDelivery' ([#262](https://github.com/VDVde/OJP/pull/262))
* Additional 'OptimisationMethod's for trip planning ('environmentalSafety', 'extraSafe', 'extraReliable', 'scenic', 'quietTravel'), new 'HikingProfile' and 'CyclingProfile', support for mutiple 'OptimisationMethod's, new filter 'IncludeAlternativeOptions' to show second-best routes ([#302](https://github.com/VDVde/OJP/pull/302))
* New place sorting options ('PlaceSortingGroup') for 'OJPLocationInformationRequest' ([#301](https://github.com/VDVde/OJP/pull/301))

2023-01-25 09:56 UTC, trurlurl reviewed
Updates to V1.1

2023-01-25 10:11 UTC, trurlurl reviewed
Another trial to commit from the web editor...

2023-01-25 10:13 UTC, trurlurl commented on CHANGELOG.md
> +* New `OJPLineInformationRequest` and `OJPLineInformationDelivery`. [#243](https://github.com/VDVde/OJP/pull/243)
```suggestion
```

2023-01-25 10:14 UTC, trurlurl commented on CHANGELOG.md
> +### Changed
```suggestion
```

2023-01-25 10:14 UTC, trurlurl commented on CHANGELOG.md
> +### Removed
```suggestion
```

2023-01-25 10:17 UTC, trurlurl commented on CHANGELOG.md
> +## [1.1] - Not released yet (will be released as part of 2.0)
The following updates should  be added to V1.1:

Added
* Added new files *README.md* and this *CHANGELOG.md*. [#130](https://github.com/VDVde/OJP/pull/130)

Removed
* Removed annotations in `choice` constructs. [#157](https://github.com/VDVde/OJP/pull/157)

2023-01-25 10:42 UTC, ue71603 commented
@trurlurl Some of the changes should be moved to the category "Breaking", we can also do this later.

2023-04-25 08:20 UTC, trurlurl requested changes
Reflects merged PRs as of 24.4.23. Likely to be added next: #353, #447, #349, #363, #328, #341.

2023-04-25 08:20 UTC, trurlurl commented on CHANGELOG.md
> +* New `OJPAvailabilityRequest` and `OJPAvailabilityDelivery`. [#262](https://github.com/VDVde/OJP/pull/262), [#241](https://github.com/VDVde/OJP/pull/241)
```suggestion
* New `OJPAvailabilityRequest` and `OJPAvailabilityDelivery`. [#262](https://github.com/VDVde/OJP/pull/262), [#241](https://github.com/VDVde/OJP/pull/241), [#322](https://github.com/VDVde/OJP/pull/322)
```

2023-04-25 08:20 UTC, trurlurl commented on CHANGELOG.md
> +* Additional enumeration values for `MultiPointType` (`OJPMultiPointTripRequest`), added `ViaSytem` for `OJPTripRequest` and `OJPMultiPointTripRequest`, added `SustainabilityGroup` with `EmissionCO2`
```suggestion
* Additional enumeration values for `MultiPointType` (`OJPMultiPointTripRequest`), added `ViaSytem` for `OJPTripRequest` and `OJPMultiPointTripRequest`, added `SustainabilityGroup` with `EmissionCO2`, added `Priority` for exchange points, renamed `ReferredSystemId` and `AllowedSystemId` to `ReferredSystem` and `AllowedSystem`, respectively. [#244](https://github.com/VDVde/OJP/pull/244), [#344](https://github.com/VDVde/OJP/pull/344)
```

2023-04-25 08:20 UTC, trurlurl commented on CHANGELOG.md
> +* New OJP.spp (XML Spy project file). [#297](https://github.com/VDVde/OJP/pull/297)
```suggestion
* Introduced more specific ObjectIdTypes for NeTEx objects: `FareResultObjectIdType`, `StopEventResultObjectIdType`, `TripResultObjectIdType`, `MultiPointTripResultObjectIdType`, `TripObjectIdType`, `LegObjectIdType`, `PlaceObjectIdType`. [#316](https://github.com/VDVde/OJP/pull/316),  [#348](https://github.com/VDVde/OJP/pull/348)
* New OJP.spp (XML Spy project file). [#297](https://github.com/VDVde/OJP/pull/297)
```

2023-04-25 08:20 UTC, trurlurl commented on CHANGELOG.md
> +
```suggestion

* Replaced `TravelClass` with `siri:FareClass` which uses the NeTEx enumeration values. [#354](https://github.com/VDVde/OJP/pull/354)
* Reorganised `BaseTripPolicyGroup` so as to align the parameters in `MultiPointTripPolicyGroup` with `TripPolicyGroup` [#333](https://github.com/VDVde/OJP/pull/333)
* Renamed `OJP_Places.xsd` to `OJP_Location.xsd`, `OJP_PlaceSupport.xsd` to `OJP_LocationSupport.xsd`, `OJPPlaceInformationRequest` to `OJPLocationInformationRequest`, as well as the related Delivery, structures and groups; renamed `Place` to `Location` in the StopEvent service and `TripPlace` to `TripLocation`. [#231](https://github.com/VDVde/OJP/pull/231)
* Updated to SIRI 2.1 using a copy and adapted imports. [#330](https://github.com/VDVde/OJP/pull/330)
* Corrected several typos.  [#320](https://github.com/VDVde/OJP/pull/320),  [#343](https://github.com/VDVde/OJP/pull/343)
```

2023-04-25 08:20 UTC, trurlurl commented on CHANGELOG.md
> +
```suggestion

* Added `AreaGeometry` to `LineResultStructure`.  [#337](https://github.com/VDVde/OJP/pull/337)
* New `OJPErrorStructure` both at the level of the `xDelivery` and at the level of the `xResult`. [#336](https://github.com/VDVde/OJP/pull/336)
* Added `IsAlternativeOption` to `TripResultStructure`.  [#326](https://github.com/VDVde/OJP/pull/326)
* Added `FareEstimated` to `FareResultStructure`.  [#324](https://github.com/VDVde/OJP/pull/324)
* Added `TripContext` to `TripFareRequestStructure` and `MultiTripFareRequestStructure`.  [#323](https://github.com/VDVde/OJP/pull/323)
* New `OperatorFilter`and `SystemId` in `TripRefineRequest` to indicate the system to be queried. [#298](https://github.com/VDVde/OJP/pull/298)
* Added `ExpectedDepartureOccupancy` and `ExpectedDepartureCapacities` (from SIRI) to Legs.  [#264](https://github.com/VDVde/OJP/pull/264)
* New `OJPStatusRequest`and `OJPStatusDelivery`. [#216](https://github.com/VDVde/OJP/pull/216)
```

2023-04-25 08:28 UTC, trurlurl commented on CHANGELOG.md
```suggestion

* Added *README.md* and this *CHANGELOG.md* files. [#130](https://github.com/VDVde/OJP/pull/130)
```

2023-04-25 08:32 UTC, trurlurl commented on CHANGELOG.md
> +## [1.1] - Not released yet (will be released as part of 2.0)
First item done (#130), still TODO: add line for #157.

2023-04-25 08:38 UTC, trurlurl requested changes
Moved #330 to *breaking*.

2023-04-25 08:38 UTC, trurlurl commented on CHANGELOG.md
> +* Updated to SIRI 2.1 using a copy and adapted imports. [#330](https://github.com/VDVde/OJP/pull/330)
```suggestion
```

2023-04-25 08:38 UTC, trurlurl commented on CHANGELOG.md
> +
```suggestion

* Updated to SIRI 2.1 using a copy and adapted imports. [#330](https://github.com/VDVde/OJP/pull/330)
```

2023-05-31 20:25 UTC, ue71603 commented
@trurlurl 
The headings should perhaps a bit changed.
I think new service/added/changed/removed would be the titles. The distinction between 1.1 and 2.0 can be removed (as we only have 2.0).
We should mark changes as breaking, when formerly valid examples are no longer valid:
* changes of element names
* changes of structure that are not compatible
* optional elements that are now mandatory
* enum values removed/altered
* type of an element changed (more restrictive/incompatible alteration).
Perhaps we should mark each such line with "[breaking]". 
What do you think?

2023-06-08 12:36 UTC, trurlurl commented on CHANGELOG.md
> +## [1.1] - Not released yet (will be released as part of 2.0)
157 DONE as well.

2023-08-21 08:09 UTC, skinkie approved these changes

2023-11-07 12:04 UTC, trurlurl commented
We are ready, the list is complete & up to date.

2023-11-07 12:14 UTC, skinkie approved these changes

2023-11-07 12:40 UTC, ue71603 commented
@trurlurl when you accept, we can merge it...

2023-11-07 13:16 UTC, merged