Added Transmodel TRIP REQUEST.Flexibilitywindow
VDVde/OJP pull request #372
Opened 2023-06-14 17:02 UTC by ue71603

2023-06-19 11:42 UTC, normanoffel commented
What is the use case for this field? When should it be filled and what are its implications / what are the expectations from the enquirers?

2023-06-20 12:10 UTC, herlitze approved these changes

2023-06-20 12:15 UTC, herlitze submitted a review, later dismissed

2023-06-20 12:15 UTC, herlitze commented on OJP/OJP_JourneySupport.xsd
> +					<xs:documentation>Begin of the interval.</xs:documentation>
interval -> time range

2023-06-20 12:15 UTC, herlitze commented on OJP/OJP_JourneySupport.xsd
> +					<xs:documentation>End of the interval.</xs:documentation>
interval -> time range

2023-06-20 12:15 UTC, herlitze commented on OJP/OJP_JourneySupport.xsd
> +						<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed thatthe implementation delivers all possible arrivals and depa
- space missing in the third sentence that_the
- i would expect wither arrivals or departures: ... all possible arrivals **or** departures in the interval

2023-06-20 14:01 UTC, ue71603 commented on OJP/OJP_JourneySupport.xsd
> +					<xs:documentation>End of the interval.</xs:documentation>
```suggestion
					<xs:documentation>End of the time range.</xs:documentation>
```

2023-06-20 14:01 UTC, ue71603 commented on OJP/OJP_JourneySupport.xsd
> +						<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed thatthe implementation delivers all possible arrivals and depa
```suggestion
						<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals or departures in the time range. E.g. for airplane with +/- 3 days.</xs:documentation>
```

2023-06-20 14:08 UTC, skinkie commented on OJP/OJP_JourneySupport.xsd
> +			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed thatthe implementation delivers all possible arrivals and departu
```suggestion
			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals and departures in the interval. E.g. for airplane with +/- 3 days.</xs:documentation>
```

2023-06-20 14:09 UTC, skinkie approved these changes

2023-06-21 15:06 UTC, skinkie submitted a review, later dismissed

2023-06-21 16:40 UTC, AndreasAtSBB submitted a review, later dismissed
added new TRIP REQUEST.FlexibilityWindow with an example and also new matching error definitions.

2023-06-21 18:26 UTC, trurlurl requested changes
1) *PlaceContext* is also used in *StopEventRequest* which already contains the element *TimeWindow*. Isn't that too redundant / confusing?

2) As for the logic how to integrate *DepArrTimeRange* and *NumberOfResults** - I suppose that they are treated to indicate what the results should cover at least (i.e., each one is able to extend the number of results).

2023-06-21 18:26 UTC, trurlurl commented on OJP/OJP_JourneySupport.xsd
> +			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals and depart
```suggestion
			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals or departures in the interval. E.g. for airplane with +/- 3 days.</xs:documentation>
```

2023-06-21 22:42 UTC, ue71603 commented on OJP/OJP_JourneySupport.xsd
> +			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals or departu
```suggestion
			<xs:documentation>The acceptable time range for the arrival or departure. Implements TRIP REQUEST.FlexibilityWindow. It is assumed that the implementation delivers all possible arrivals or departures in the time range. E.g. for airplane with +/- 3 days.</xs:documentation>
```

2023-06-21 22:48 UTC, skinkie approved these changes

2023-06-22 13:13 UTC, normanoffel commented on OJP/OJP_JourneySupport.xsd
> +			</xs:element>
I would prefer a duration over a end date time specification.

2023-06-23 13:26 UTC, skinkie approved these changes

2023-06-23 13:55 UTC, trurlurl approved these changes

2023-06-23 14:00 UTC, sgrossberndt requested changes
On it

2023-06-23 14:10 UTC, sgrossberndt approved these changes
Two improvements:
* [Improve wording and fix typo in documentation](https://github.com/VDVde/OJP/pull/372/commits/ba5dff8d86640b37d5a2801c92edabb639796377)
* [Renamed problem code to TRIP_TIMEWINDOWTOOLARGE](https://github.com/VDVde/OJP/pull/372/commits/0b1328fd1ac09a69cd94eac99d10831058f2cd04) (should not contain "ERROR", will add a pull request for `TRIP_DATETIMEERROR` shortly) and since the problem is about the time window let's use that in the name of the problem as well.

2023-06-29 15:15 UTC, skinkie approved these changes

2023-06-29 15:15 UTC, merged