BookingId in FareResult
VDVde/OJP pull request #400
Opened 2023-08-18 12:16 UTC by ue71603

If a BookingId is provided in the OJPFareDelivery we need a place to put it

2023-08-18 13:33 UTC, trurlurl submitted a review, later dismissed

2023-08-18 14:05 UTC, skinkie commented on OJP/OJP_FareSupport.xsd
> +			</xs:group>
```suggestion
			</xs:group>
```

2023-08-18 14:05 UTC, skinkie approved these changes

2023-08-18 14:08 UTC, skinkie requested changes
OJP/OJP_FareSupport.xsd:709: element element: Schemas parser error : element decl. '{http://www.vdv.de/ojp}BookingId', attribute 'type': The QName value '{http://www.vdv.de/ojp}BookingObjectIdType' does not resolve to a(n) type definition.

2023-08-20 13:31 UTC, ue71603 commented
> OJP/OJP_FareSupport.xsd:709: element element: Schemas parser error : element decl. '{[http://www.vdv.de/ojp}BookingId](http://www.vdv.de/ojp%7DBookingId)', attribute 'type': The QName value '{[http://www.vdv.de/ojp}BookingObjectIdType](http://www.vdv.de/ojp%7DBookingObjectIdType)' does not resolve to a(n) type definition.

fixed it

2023-08-20 14:23 UTC, skinkie approved these changes

2023-08-20 17:59 UTC, trurlurl approved these changes

2023-08-21 10:32 UTC, herlitze approved these changes

2023-08-21 11:19 UTC, merged