Update README.md
VDVde/OJP pull request #454
Opened 2024-08-24 18:14 UTC by ue71603

add new branches

2024-08-24 19:25 UTC, trurlurl approved these changes

2024-08-25 21:42 UTC, skinkie approved these changes

2024-08-25 21:43 UTC, skinkie commented
But I don't think it is correct to say the master branch is set to. So either master is OJP 2. Or we set the default branch to OJP 2. I think the latter is what we want.

2024-08-25 21:44 UTC, skinkie requested changes
See suggestion.

2024-08-30 19:08 UTC, sgrossberndt commented
I'd like to do a general improvement of the readme before (PR in https://github.com/VDVde/OJP/pull/456) and have a "Release of OJP 2.0" commit. Since the version number has already been set in "Set OJP schema version to 2.0 (#430)" I guess there only the readme to update in order to release 2.0? I guess "Handling of MultiPointType #443" should be merged before? Or is there anything else that needs to be done before?

2024-09-05 13:18 UTC, closed without merging