Test examples to see, if everything is working with TRAVIS
VDVde/OJP pull request #85
Opened 2020-05-23 14:31 UTC by ue71603

A first set of test examples.

2020-08-28 12:40 UTC, ue71603 commented
New version.

2020-10-01 17:51 UTC, ue71603 commented
I left currently only few request /response. This should show travis is working. However, I want to know if the prefixes and the style are ok.  I will now add some examples for other services too.

2020-10-02 12:00 UTC, sgrossberndt requested changes
`examples/test_examples_switzerland/TR_001.xml` and `examples/test_examples_switzerland/TR_001.xml.tmp` are empty files, I suppose `examples/test_examples_switzerland/TR_001.xml` should contain the matching request to `examples/test_examples_switzerland/TR_001_response.xml `?

Maybe use speaking names for the files too: `LIR_002_trip_from_st_gallen_to_luzern_request.xml` / `LIR_002_trip_from_st_gallen_to_luzern_response.xml`?

2020-10-10 15:50 UTC, ue71603 commented on .travis/xmllint-check.sh
> +xmllint --noout --schema OJP.xsd examples/test_examples_switzerland/*xml
changed

2020-10-10 15:50 UTC, ue71603 commented on .travis/xmllint-check.sh
>  # xmllint --noout --schema OJP.xsd examples/subdirectory1/*xml examples/subdirectory2/*xml
changed

2020-10-10 15:51 UTC, ue71603 commented on examples/test_examples_switzerland/LIR_001_search_stop_with_name_Zuerich_Kreuzplatz.xml
> +<?xml version="1.0" encoding="UTF-8"?>
changed

2020-10-11 09:14 UTC, sgrossberndt commented
We have a build failure, which is not caused by the examples but by the OJP schema definition:
https://travis-ci.com/github/VDVde/OJP/builds/189204061#L134
@pvgrumbkow @skinkie @herlitze

2020-10-12 09:14 UTC, pvgrumbkow commented
> We have a build failure, which is not caused by the examples but by the OJP schema definition:
> https://travis-ci.com/github/VDVde/OJP/builds/189204061#L134
> @pvgrumbkow @skinkie @herlitze
>
Apparently multiple imports of SIRI XSDs cause the problem, right? But what would be the solution?

2020-10-12 09:17 UTC, skinkie commented
@pvgrumbkow the rationale here was: inform the SIRI WG. My previous attempt: fix this locally.

2020-10-12 09:28 UTC, pvgrumbkow commented
Hmm, the warning message doesn't sound like a SIRI issue to me. It states that OJP_Requests.xsd tries to import a SIRI XSD which was already imported by OJP.xsd. Where is the SIRI issue then?
By the way: This is a warning. Why does it prevent building?

2020-11-10 14:49 UTC, ue71603 commented
I think the problem is with the way the import is done in the examples. I will try some other things.  I wasn't really happy there, but it worked wid XML Spy.
I hope that I can do this this evening, so we have examples tomorrow.

2020-11-10 14:50 UTC, ue71603 commented
sgrossberdt: Why is your change still blocking? As far as I can see, it should be resolved.

2020-11-10 15:41 UTC, sgrossberndt commented
As I wrote the issues which make the build fail are not due to your examples, @ue71603 - the build failure is caused by the OJP XSD schema definition itself.

2020-11-10 17:18 UTC, sgrossberndt commented
Ok, so I identified several issues:

The ominous *.tmp files which are occurring stem from Travis CI and have not committed by @ue71603 - this happens when the linting/prettifying from https://github.com/VDVde/OJP/blob/changes_for_v1.1/.travis/xmllint-check.sh#L2 fails and leaves a *.tmp file - which is then found as difference by Travis and committed, as visible in https://github.com/VDVde/OJP/pull/85/commits/ba7ea1b4e91ff98b203be1a44c99c9d7a3514ece?file-filters%5B%5D=

The Travis log contains warnings and errors, the warnings due to the namespace "siri" being imported multiple times with different files in it, e.g. `OJP.xsd` defines SIRI as its main namespace in `xs:schema`: `xmlns="http://www.siri.org.uk/siri"`, defines the location for this schema as `<xs:include schemaLocation="siri/siri_base-v2.0.xsd"/>` and imports the namespace `http://www.vdv.de/ojp` with schema location `OJP_Requests.xsd`.
But `OJP_Requests.xsd` defines the SIRI namespace again and does this by referencing *another* SIRI XSD file: `<xs:import namespace="http://www.siri.org.uk/siri" schemaLocation="./siri/siri_requests-v2.0.xsd"/>` and also includes `OJP_Fare.xsd` which once again defines the SIRI namespace by referencing *another* SIRI XSD file: `<xs:import namespace="http://www.siri.org.uk/siri" schemaLocation="./siri_model/siri_modes-v1.1.xsd"/>`

This apparently leads to issues as some parsers (xmllint, Xerces) cannot cope with the same namespace name being bound to different schema files in imported files. Also read https://stackoverflow.com/questions/4998063/one-xml-namespace-equals-one-and-only-one-schema-file

My proposal to fix the SIRI includes in the XSD is to always use `./siri_model/siri_all-v2.0.xsd` instead of trying to shorten the number of includes SIRI files at the expense of an invalid XSD.
This will fix the SIRI includes but the examples will still be invalid, as we have the same issue with the namespace `xmlns="http://www.vdv.de/ojp"` too. Here I am still investigating on how to fix it.

2020-11-11 09:43 UTC, sgrossberndt commented
I propose to drop this branch and close the pull request in favor of https://github.com/VDVde/OJP/pull/115

2020-11-11 14:37 UTC, sgrossberndt commented
Closed in favor of https://github.com/VDVde/OJP/pull/115

2020-11-11 14:37 UTC, closed without merging