Update OJP_StopEvents.xsd
VDVde/OJP pull request #96
Opened 2020-09-26 16:31 UTC by ue71603

fixes: https://github.com/VDVde/OJP/issues/69

2020-09-28 16:05 UTC, pvgrumbkow commented on OJP_StopEvents.xsd
> +			<xs:element name="IncludeStopHierarcy" type="HierarchyEnumeration" default="no" minOccurs="0">
There's a typo in IncludeStopHierarcy.

2020-10-01 11:47 UTC, ue71603 commented on OJP_StopEvents.xsd
> +			<xs:element name="IncludeStopHierarcy" type="HierarchyEnumeration" default="no" minOccurs="0">
Typo corrected.

2020-10-02 12:48 UTC, sgrossberndt submitted a review, later dismissed

2020-10-03 00:54 UTC, sgrossberndt requested changes

2020-10-03 00:54 UTC, sgrossberndt commented on OJP_StopEvents.xsd
>  			<xs:element name="IncludeStopHierarchy" type="HierarchyEnumeration" default="no" minOccurs="0">
"local" was defined as default in the documentation but the actual in the attribute still is `default="no"`

2020-10-03 11:11 UTC, sgrossberndt approved these changes

2020-10-12 13:44 UTC, pvgrumbkow approved these changes

2020-10-12 13:56 UTC, merged